### ISSUE TITLE
Can't install on windows.

### ISSUE THREAD

**Issue by konung** [oggy/looksee#17]
Hello.

Trying to build on windows - no luck. Here is my error message ( running on Ruby 1.9.2 p290 on windows 7 with devkit ). 

PS D:\Projects\Web\ajrintl.com\ajr> gem install looksee
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing looksee:
        ERROR: Failed to build gem native extension.

```
    C:/ruby/Ruby192/bin/ruby.exe extconf.rb
```

creating Makefile

make
C:/ruby/Ruby192/bin/ruby -e "puts 'EXPORTS', 'Init_mri'"  > mri-i386-mingw32.def
gcc -I. -IC:/ruby/Ruby192/include/ruby-1.9.1/i386-mingw32 -I/C/ruby/Ruby192/include/ruby-1.9.1/ruby/backward -I/C/ruby/Ruby192/include/ruby-1.9.1 -Imri   -DRUBY_VERSION=192 -Imri/1.9.2 -O3 -g -Wextra
-Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -o mri.o -c mri/mri.c
In file included from mri/mri.c:9:0:
mri/1.9.2/vm_core.h:27:26: fatal error: thread_win32.h: No such file or directory
compilation terminated.
make: **\* [mri.o] Error 1

Did anyone have any luck with this? Thank you

**Comment by mathieujobin** [comment]
I almost rebooted to try it... 

anyone can try on ruby 2.2.5 or 2.3.1 ?

**Comment by mathieujobin** [comment]
Linux for me ;) close?

**Comment by oggy** [comment]
Closing this because it's a wee bit old, and I don't expect to have time to get a Windows build working myself. Would be open to patches of course.
