### ISSUE TITLE
Installing On Mac OSX Lion

### ISSUE THREAD

**Issue by smojtabai** [oggy/looksee#29]
Building native extensions.  This could take a while...
ERROR:  Error installing looksee:
	ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.1.2/bin/ruby extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling mri/mri.c
In file included from mri/2.1.0/method.h:14,
                 from mri/mri.c:4:
mri/2.1.0/internal.h:209: error: expected ‘;’, ‘,’ or ‘)’ before ‘x’
make: *** [mri.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.1.2@malibu/gems/looksee-2.1.1 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.1.2@malibu/extensions/x86_64-darwin-13/2.1.0-static/looksee-2.1.1/gem_make.out

I tried all the suggestions in a previous issue (upgraded xcode to 4.6). Here is gcc:

Using built-in specs.
Target: i686-apple-darwin11
Configured with: /private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/src/configure --disable-checking --enable-werror --prefix=/Applications/Xcode.app/Contents/Developer/usr/llvm-gcc-4.2 --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin11 --enable-llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/dst-llvmCore/Developer/usr/local --program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11 --target=i686-apple-darwin11 --with-gxx-include-dir=/usr/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

I tried uninstall reinstalling ruby after updating xcode but still no go.

**Comment by oggy** [comment]
I haven't been able to repro this, although I don't have a pristine Mac to experiment on either.

I recently upgraded to Yosemite using latest brews & rvm, and had no problems. Xcode 6.1.1 with gcc:

    $ gcc -v
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
    Target: x86_64-apple-darwin14.0.0
    Thread model: posix

Closing this, as I don't think there's anything more I can do with this info.

**Comment by steffejr** [comment]
Did anyone get this resolved? I have the same problem. I have OsX 10.8.5.

Thanks

**Comment by oggy** [comment]
@steffejr It was never resolved, sorry.
