### ISSUE TITLE
Make looksee Ruby only - A.K.A Ruby 2.4 support ;)

### ISSUE THREAD

**Issue by mathieujobin** [oggy/looksee#42]
@oggy  Did you see this?

https://github.com/ruby/ruby/compare/trunk...nobu:feature/12655

**Comment by oggy** [comment]
Thanks, I hadn't seen that!

It's great to see, although as far as I can tell that isn't in trunk yet, so closing this for now.

**Comment by mathieujobin** [comment]
Shall we bump that thread on https://bugs.ruby-lang.org/issues/12655
And request it to be merged into trunk?
or test it before end?

I cherry-pick'ed the top commit on top of recent trunk.

https://github.com/ruby/ruby/compare/trunk...mathieujobin:feature/12655

**Comment by mathieujobin** [comment]
too late for ruby 2.7
but PR is open with the two added public methods to ruby

https://github.com/ruby/ruby/pull/2778

**Comment by mathieujobin** [comment]
https://bugs.ruby-lang.org/issues/12655 has been accepted to be included in future Ruby, likely 3.2 coming out this december.
The patch has been updated.

I wonder if anyone would have the time to try to integrate looksee with it ?

**Comment by oggy** [comment]
Whoa nice! I thought they had rejected it when the idea was floated 5 years (!) ago.

I'll take a look if I can get that build going.

**Comment by mathieujobin** [comment]
The patch has been merged in ruby trunk, which means it's available if you build ruby-head

```
Issue #12655 has been updated by jeremyevans (Jeremy Evans).

Status changed from Feedback to Closed

Applied in changeset commit:git|7cda7fbbdc14f4262afaa94cdeb5a5987f1eb01a.

----------
Add Module#undefined_instance_methods

Implements [Feature #12655]

Co-authored-by: Nobuyoshi Nakada <[nobu@ruby-lang.org](mailto:nobu@ruby-lang.org)>

----------------------------------------
Feature #12655: Accessing the method visibility
https://bugs.ruby-lang.org/issues/12655#change-97856
```
