### ISSUE TITLE
Add support for truffleruby.

### ISSUE THREAD

**Issue by zw963** [oggy/looksee#48]
excellent [truffler](https://github.com/oracle/truffleruby) on his toword 1.0.0 way. (1.0.0 RC6 soon), it now  support mysql2 pg, nokogiri etc, i think maybe it is the time have a try in little ruby production project., 

i want to know weather it is possible to worked with Looksee.

Thanks

**Comment by oggy** [comment]
I haven't looked at Truffle yet, or what it would take to support it. Would be cool, though.

**Comment by zw963** [comment]
In fact, i never use truffle for now, so, just close it anyway.
