### ISSUE TITLE
Support for Ruby 3

### ISSUE THREAD

**Issue by kapso** [oggy/looksee#54]
Requesting support for Ruby 3.

Thanks.

**Comment by mathieujobin** [comment]
https://github.com/oggy/looksee/pull/55

**Comment by kapso** [comment]
@oggy any plans of merging #55 ?

@mathieujobin thanks much 🙏

**Comment by mathieujobin** [comment]
https://github.com/oggy/looksee/pull/55#issuecomment-760108294

**Comment by oggy** [comment]
Merged!
