### ISSUE TITLE
not output correct when use with irb. (it works with pry)

### ISSUE THREAD

**Issue by zw963** [oggy/looksee#57]
Following is output.

```sh
^[[1;37m[Roda::RodaPlugins::Sprockets::Task instance]^[[0m
  ^[[1;32mbindings^[[0m                     ^[[1;32mirb_cwb^[[0m                      ^[[1;32mkill^[[0m       
  ^[[1;32mcb^[[0m                           ^[[1;32mirb_cws^[[0m                      ^[[1;32mls^[[0m         
  ^[[1;32mchws^[[0m                         ^[[1;32mirb_cwws^[[0m                     ^[[1;32mmeasure^[[0m    
  ^[[1;32mconf^[[0m                         ^[[1;32mirb_pop_binding^[[0m              ^[[1;32mpopb^[[0m       
  ^[[1;32mcontext^[[0m                      ^[[1;32mirb_popb^[[0m                     ^[[1;32mpopws^[[0m      
  ^[[1;32mcws^[[0m                          ^[[1;32mirb_popws^[[0m                    ^[[1;32mpushb^[[0m      
  ^[[1;32mcwws^[[0m                         ^[[1;32mirb_print_working_binding^[[0m    ^[[1;32mpushws^[[0m     
  ^[[1;32mexit^[[0m                         ^[[1;32mirb_print_working_workspace^[[0m  ^[[1;32mpwws^[[0m       
  ^[[1;32mfg^[[0m                           ^[[1;32mirb_push_binding^[[0m             ^[[1;32mquit^[[0m       
  ^[[1;32mhelp^[[0m                         ^[[1;32mirb_pushb^[[0m                    ^[[1;32mshow_source^[[0m
  ^[[1;32mirb_bindings^[[0m                 ^[[1;32mirb_pushws^[[0m                   ^[[1;32msource^[[0m     
  ^[[1;32mirb_cb^[[0m                       ^[[1;32mirb_pwb^[[0m                      ^[[1;32mwhereami^[[0m   
  ^[[1;32mirb_change_binding^[[0m           ^[[1;32mirb_pwws^[[0m                     ^[[1;32mworkspaces^[[0m 
  ^[[1;32mirb_chws^[[0m                     ^[[1;32mirb_quit^[[0m                   
  ^[[1;32mirb_current_working_binding^[[0m  ^[[1;32mjobs^[[0m    
```

I consider this is not same reason as https://github.com/oggy/looksee#ansi-escapes, because outout not same, and when i set `export LESS='-R'` instead, still get same result.

But `ls` works quite well with pry, test it on ruby 2.7.1 and ruby 3.0.2

Thank you.

**Comment by zw963** [comment]
Any idea?

**Comment by mathieujobin** [comment]
this is not new. it depends on your terminal settings.
linux terminal colors not showing properly
are you via SSH?
Its hard to tell what terminal setting is incorrect. 
but your terminal is detected as non-color compliant.
the only thing `looksee` could do is detect that setting and print a warning and remove colors from the output.
I'll review the PR if you want to work on it.

**Comment by zw963** [comment]
> this is not new. it depends on your terminal settings. linux terminal colors not showing properly are you via SSH? Its hard to tell what terminal setting is incorrect. but your terminal is detected as non-color compliant. the only thing `looksee` could do is detect that setting and print a warning and remove colors from the output. I'll review the PR if you want to work on it.

I use a very popular terminal, `konsole`, the offical terminal of kde plasma.

same terminal, it work well with pry, but not work with irb, so, i consider this is compatibility issue?

**Comment by mathieujobin** [comment]
Actually, I also use `konsole` from Kubuntu 21.04
I have same problem as you with ruby 2.6.8, but it works fine with 2.7.4

I don't know what other difference it can be...

**Comment by zw963** [comment]
Hi, i can exact reproduce this again on ruby 3.0.3.

1. create a new project
2. create a Gemfile, with only looksee added.
3.  run bundle install
4. RUBYOPT= RUBYLIB= bundle exec irb
5. require 'looksee' in irb
6. Looksee["hello"]

will output result like this:

![image](https://user-images.githubusercontent.com/549126/145381821-8e80ca6e-a75c-45dd-84fd-a7ce7c49701e.png)

Following is my load path.

```
3.0.3 :001 > puts $LOAD_PATH
/home/zw963/others/.rvm/gems/ruby-3.0.3@test_break/gems/looksee-4.4.0/lib
/home/zw963/others/.rvm/gems/ruby-3.0.3@test_break/extensions/x86_64-linux/3.0.0/looksee-4.4.0
/home/zw963/others/.rvm/rubies/ruby-3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib
/home/zw963/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0
/home/zw963/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/x86_64-linux
/home/zw963/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby
/home/zw963/.rvm/rubies/ruby-3.0.3/lib/ruby/vendor_ruby/3.0.0
/home/zw963/.rvm/rubies/ruby-3.0.3/lib/ruby/vendor_ruby/3.0.0/x86_64-linux
/home/zw963/.rvm/rubies/ruby-3.0.3/lib/ruby/vendor_ruby
/home/zw963/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0
/home/zw963/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/x86_64-linux
 => nil 
```

**Comment by zw963** [comment]
Hi, i try on this gem on a very bare arch linux system, no any dot config, no any environment variable.

use RVM install ruby 3.0.3

I just create a new Gemfile like this:

```rb
source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'looksee'
```

create a new `1.rb` file like this:



```rb
require 'looksee'
binding.irb
```

then `bundle exec ruby 1.rb`,  run `Looksee["hello"]`, get same raw characters.

![image](https://user-images.githubusercontent.com/549126/147113538-ff368e3c-6f77-4f9f-9e85-1cf097612439.png)


I can reproduce it on kitty terminal use arch linux too.

**Comment by zw963** [comment]
Hi, i can reproduce this on a new installed virtualbox with arch linux.

![image](https://user-images.githubusercontent.com/549126/147136527-1d6f4393-23b9-4df8-a876-5a461a0e1a55.png)

As you can see, it works well with pry in virtualbox too.

![image](https://user-images.githubusercontent.com/549126/147136692-9a23a75d-7303-41d0-b3a1-f2cbf8197a41.png)

so, i consider some changes for Irb cause this?

Thank you.

**Comment by zw963** [comment]
I can reproduce this on ruby 3.1.0

**Comment by mathieujobin** [comment]
set this before calling `irb`

```ruby
IRB.conf[:USE_COLORIZE] = false
```

**Comment by zw963** [comment]
> set this before calling `irb`
> 
> ```ruby
> IRB.conf[:USE_COLORIZE] = false
> ```

It works on both 3.0.3 and 3.1.0, thank you.

**Comment by zw963** [comment]
Hi, @mathieujobin , is there possible only set `IRB.conf[:USE_COLORIZE] = false` in looksee gem only before start irb session?

if use `IRB.conf[:USE_COLORIZE] = false` as default, all irb code is no color. (see screenshot)

![image](https://user-images.githubusercontent.com/549126/194042580-578da537-008b-4bb9-8f77-6a0901c5513d.png)

**Comment by zw963** [comment]
I found, if we change [this](https://github.com/ruby/ruby/blob/v3_1_2/lib/irb/context.rb#L56) line into `@use_colorize = IRB.conf[:USE_COLORIZE]`, it works perfect, that is, code is colorful, and looksee output is colorful too.

**Comment by oggy** [comment]
Fixed in 5.0.0. Note that the looksee helper has changed from `ls` to `look` to silence the warning. Of course you can still alias it back with `Looksee.rename`.

This is making me wonder if ruby-core would be interested in adding other Looksee features into that `ls` command. Then this gem wouldn't need to exist anymore.

**Comment by mathieujobin** [comment]
Thank you @oggy 

I don't know if anyone is using the new visibility methods *we* have requested for... 

From ruby 3.2, looksee should be able to go without the C extension at least... 

I'm not sure if I'll ever get used to type Object#look, I'm too used to `.ls`

Thanks for your excellent gem.

**Comment by oggy** [comment]
Looksee 5 uses `undefined_instance_methods`, but still uses the extension to get the instance of a `singleton_class`. As far as I know, ruby still does not expose this.

We could probably refactor things a bit to get around this for most cases, but in the (admittedly pathological) case of a singleton class of a singleton class, it's nice to have this.
