### ISSUE TITLE
build on ruby 3.2.0?

### ISSUE THREAD

**Issue by zw963** [oggy/looksee#59]
Thanks.

**Comment by mathieujobin** [comment]
Have you tried it ?

**Comment by mathieujobin** [comment]
I believe the new functions proposed in https://github.com/oggy/looksee/issues/42
we're merged into ruby 3.2, so if there is any problem with the C extension, it could be the occasion to try porting the gem to the new ruby visibility methods.

**Comment by zw963** [comment]
Oops, it works on 3.2.0-preview1 for linux, thanks!

**Comment by oggy** [comment]
Just pushed 5.0.0 which restores undefined_methods in 3.2.0-preview2.
