### ISSUE TITLE
problem in rails console

### ISSUE THREAD

**Issue by aziz** [oggy/looksee#6]
when I run lp [] in irb everything is fine, but when running the same command in rails console I get something like this:

ESC[1;37mArrayESC[0m
 ESC[1;32m&ESC[0m         ESC[1;32mcompact!ESC[0m    ESC[1;32minclude?ESC[0m  
ESC[1;32mrassocESC[0m        ESC[1;32mto_aESC[0m           

the ansi colors are working fine in irb but in rails console they just make a mess in way that makes it unusable!

**Comment by oggy** [comment]
Thanks!
